-- ============================================================
-- MACS System – Oracle Init Script
-- Target: gvenzl/oracle-free:23-slim (FREEPDB1)
-- ============================================================

CREATE USER macs IDENTIFIED BY macs_password
    DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, UNLIMITED TABLESPACE TO macs;

ALTER SESSION SET CURRENT_SCHEMA = macs;

-- ============================================================
-- Config Server – PROPERTIES
-- ============================================================
CREATE TABLE PROPERTIES (
    APPLICATION  VARCHAR2(128)  NOT NULL,
    PROFILE      VARCHAR2(128)  NOT NULL,
    LABEL        VARCHAR2(128)  NOT NULL,
    PROP_KEY     VARCHAR2(256)  NOT NULL,
    PROP_VALUE   VARCHAR2(4000),
    CONSTRAINT PK_PROPERTIES PRIMARY KEY (APPLICATION, PROFILE, LABEL, PROP_KEY)
);

-- ============================================================
-- Auth Server – System / Connector / Group 구조
-- ============================================================

-- 시스템-커넥터 매핑
CREATE TABLE SYSTEM_CONNECTOR (
    SYSTEM_NAME     VARCHAR2(64)   NOT NULL,
    CONNECTOR_NAME  VARCHAR2(128)  NOT NULL,
    DESCRIPTION     VARCHAR2(512),
    CREATED_AT      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SYSTEM_CONNECTOR PRIMARY KEY (SYSTEM_NAME, CONNECTOR_NAME)
);

-- 그룹 (시스템 단위, 자동 ID)
CREATE TABLE GROUP_INFO (
    GROUP_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    SYSTEM_NAME  VARCHAR2(64)   NOT NULL,
    GROUP_NAME   VARCHAR2(128)  NOT NULL,
    CONSTRAINT PK_GROUP_INFO  PRIMARY KEY (GROUP_ID),
    CONSTRAINT UQ_GI_SYS_GRP UNIQUE (SYSTEM_NAME, GROUP_NAME)
);

-- 그룹 멤버
CREATE TABLE GROUP_MEMBER (
    GROUP_ID         NUMBER        NOT NULL,
    EMPLOYEE_NUMBER  VARCHAR2(32)  NOT NULL,
    CONSTRAINT PK_GROUP_MEMBER PRIMARY KEY (GROUP_ID, EMPLOYEE_NUMBER),
    CONSTRAINT FK_GM_GROUP     FOREIGN KEY (GROUP_ID) REFERENCES GROUP_INFO (GROUP_ID)
);

CREATE INDEX IDX_GM_EMPLOYEE ON GROUP_MEMBER (EMPLOYEE_NUMBER);

-- 그룹 리소스 (커넥터 이름)
CREATE TABLE GROUP_RESOURCE (
    GROUP_ID       NUMBER         NOT NULL,
    RESOURCE_NAME  VARCHAR2(256)  NOT NULL,
    CONSTRAINT PK_GROUP_RESOURCE PRIMARY KEY (GROUP_ID, RESOURCE_NAME),
    CONSTRAINT FK_GR_GROUP       FOREIGN KEY (GROUP_ID) REFERENCES GROUP_INFO (GROUP_ID)
);

-- 개인 리소스
CREATE TABLE USER_RESOURCE (
    EMPLOYEE_NUMBER  VARCHAR2(32)   NOT NULL,
    SYSTEM_NAME      VARCHAR2(64)   NOT NULL,
    RESOURCE_NAME    VARCHAR2(256)  NOT NULL,
    CONSTRAINT PK_USER_RESOURCE PRIMARY KEY (EMPLOYEE_NUMBER, SYSTEM_NAME, RESOURCE_NAME)
);

-- ============================================================
-- Admin Server – AUDIT_LOG
-- ============================================================
CREATE TABLE AUDIT_LOG (
    AUDIT_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    OCCURRED_AT      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EMPLOYEE_NUMBER  VARCHAR2(32),
    ACTION           VARCHAR2(64)   NOT NULL,
    TARGET_TYPE      VARCHAR2(64),
    TARGET_ID        VARCHAR2(256),
    RESULT           VARCHAR2(32),
    DETAIL           VARCHAR2(4000),
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);

CREATE INDEX IDX_AUDIT_LOG_OCCURRED ON AUDIT_LOG (OCCURRED_AT);
CREATE INDEX IDX_AUDIT_LOG_EMPLOYEE ON AUDIT_LOG (EMPLOYEE_NUMBER);

-- ============================================================
-- Admin Server – CONNECTOR (metadata layer over gateway routes)
-- ============================================================
CREATE TABLE CONNECTOR (
    ID           VARCHAR2(128)  NOT NULL,
    TITLE        VARCHAR2(256)  NOT NULL,
    DESCRIPTION  VARCHAR2(1024),
    TYPE         VARCHAR2(16)   NOT NULL,
    CREATED_AT   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CONNECTOR PRIMARY KEY (ID),
    CONSTRAINT CK_CONNECTOR_TYPE CHECK (TYPE IN ('agent','api','mcp'))
);

-- ============================================================
-- Admin Server – PERMISSION (user-to-route access grants)
-- ============================================================
CREATE TABLE PERMISSION (
    APP_NAME         VARCHAR2(64)   NOT NULL,
    EMPLOYEE_NUMBER  VARCHAR2(32)   NOT NULL,
    SYSTEM           VARCHAR2(64)   NOT NULL,
    CONNECTOR        VARCHAR2(128)  NOT NULL,
    ROLE             VARCHAR2(32)   NOT NULL,
    CREATED_AT       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_PERMISSION PRIMARY KEY (APP_NAME, EMPLOYEE_NUMBER, SYSTEM, CONNECTOR)
);

CREATE INDEX IDX_PERMISSION_USER ON PERMISSION (APP_NAME, EMPLOYEE_NUMBER);

-- ============================================================
-- Sample Data – PROPERTIES
-- ============================================================
INSERT INTO PROPERTIES VALUES ('application','default','main','management.endpoints.web.exposure.include','health,info,prometheus');
INSERT INTO PROPERTIES VALUES ('gateway-service','default','main','spring.cloud.gateway.routes[0].id','portal-route');
INSERT INTO PROPERTIES VALUES ('gateway-service','default','main','spring.cloud.gateway.routes[0].uri','http://portal:3000');
INSERT INTO PROPERTIES VALUES ('gateway-service','default','main','spring.cloud.gateway.routes[0].predicates[0]','Path=/portal/**');
INSERT INTO PROPERTIES VALUES ('gateway-service','default','main','spring.cloud.gateway.routes[0].filters[0]','StripPrefix=1');

-- ============================================================
-- Sample Data – PERMISSION (role-based, logical connector)
-- ============================================================
-- 2078432: portal admin — 모든 portal 자원 사용 가능
INSERT INTO PERMISSION (APP_NAME,EMPLOYEE_NUMBER,SYSTEM,CONNECTOR,ROLE)
  VALUES ('portal','2078432','common','portal','admin');

-- 2065162: portal user — 커넥터 연동 페이지만
INSERT INTO PERMISSION (APP_NAME,EMPLOYEE_NUMBER,SYSTEM,CONNECTOR,ROLE)
  VALUES ('portal','2065162','common','portal','user');

COMMIT;
